enc:
# TODO: implement autosize
# test config for S-57
  size: [ 2.5, 1 ]
  origin: [ 17.5, 54.0 ]
  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  crs: "WGS84"
  S57_layers:
    "TSSLPT": "#8B0000"
    "CTNARE": "#964B00"
  resources: [ "data/", "data/db/PL2MP500/4/0" ]

  # test config for FGDB
  # size: [ 9000, 5062 ]
  # center: [ 44300, 6956450 ]
  # depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  # crs: "UTM33N"
  # resources: [ "data/db/Basisdata.gdb" ]

  time:
    time_start: "02-10-2024 11:00"
    time_end: "02-10-2024 14:00"
    period: "hour"
    period_multiplier: 1
#  weather:
#    PyThor_adress: "http://127.0.0.1:5000"
#    time_start: 1717931596
#    time_end: 1717952909
#    variables: [ "wave_height" ]

# test config for FGDB
#  size: [ 9000, 5062 ]
#  center: [ 44300, 6956450 ]
#  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
#  crs: "UTM33N"
#  resources: [ "/", "data/", "data/db/" ]
  ais:
    module: "live"
    #connection_string: "data/ais.db"
    #coords_type: "lonlat"
    interval: 60

    #PL STREAM
    address: "195.182.206.250"
    port: 54321

    #NO STREAM
    # address: "153.44.253.27"
    # port: 5631
    colors:
       "default"             : "#FFFFFF"
    #   "WIG"                 : "#FF5733",
    #   "FISHING"             : "#FF8C00",
    #   "TOWING"              : "#FFD700",
    #   "TOWING_EXCEED"       : "#FF4500",
    #   "DREDGING_UNDERWATER" : "#8A2BE2",
    #   "DIVING OPS"          : "#4682B4",
    #   "MILITARY OPS"        : "#696969",
    #   "SAILING"             : "#00FF7F",
    #   "PLEASURE CRAFT"      : "#FF69B4",
    #   "HSC"                 : "#4B0082",
    #   "HSC_A"               : "#800080",
    #   "HSC_B"               : "#9370DB",
    #   "HSC_C"               : "#8B0000",
    #   "HSC_D"               : "#B22222",
    #   "PILOT"               : "#00008B",
    #   "RESCUE"              : "#FFFFFF",
    #   "TUG"                 : "#D2691E",
    #   "PORT TENDER"         : "#8B4513",
    #   "ANTI_POLLUTION_EQ"   : "#20B2AA",
    #   "LAW_ENFORCEMENT"     : "#000080",
    #   "LOCAL_VESSEL"        : "#32CD32",
    #   "MEDICAL TRANSPORT"   : "#FF6347",
    #   "NONCOMBATANT"        : "#778899",
    #   "PASSENGER"           : "#1E90FF",
    #   "PASSENGER_A"         : "#00CED1",
    #   "PASSENGER_B"         : "#40E0D0",
    #   "PASSENGER_C"         : "#4682B4",
    #   "PASSENGER_D"         : "#5F9EA0",
    #   "CARGO"               : "#DAA520",
    #   "CARGO_A"             : "#B8860B",
    #   "CARGO_B"             : "#CD853F",
    #   "CARGO_C"             : "#D2B48C",
    #   "CARGO_D"             : "#A0522D",
    #   "TANKER"              : "#A52A2A",
    #   "TANKER_A"            : "#FF4500",
    #   "TANKER_B"            : "#FF6347",
    #   "TANKER_C"            : "#FFA07A",
    #   "TANKER_D"            : "#FA8072",
    #   "OTHER"               : "#696969",
    #   "OTHER_A"             : "#708090",
    #   "OTHER_B"             : "#778899",
    #   "OTHER_C"             : "#A9A9A9",
    #   "OTHER_D"             : "#D3D3D3"


display:
  colorbar: False
  dark_mode: True
  fullscreen: False
  resolution: 640
  anchor: "center"
  dpi: 96