enc:
# TODO: implement autosize
# test config for S-57
  size: [ 2.5, 1 ]
  origin: [ 17.5, 54.0 ]
  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  crs: "WGS84"
  S57_layers:
    "TSSLPT": "#8B0000"
    "CTNARE": "#964B00"
  resources: [ "data/", "data/db/PL2MP500/4/0" ]
 
  # test config for FGDB
  # size: [ 9000, 5062 ]
  # center: [ 44300, 6956450 ]
  # depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  # crs: "UTM33N"
  # resources: [ "data/db/Basisdata.gdb" ]
 
  time:
    time_start: "02-10-2024 11:00"
    time_end: "02-10-2024 15:00"
    period: "hour"
    period_multiplier: 1
#  weather:
#    PyThor_adress: "http://127.0.0.1:5000"
#    time_start: 1717931596
#    time_end: 1717952909
#    variables: [ "wave_height" ]
 
# test config for FGDB
#  size: [ 9000, 5062 ]
#  center: [ 44300, 6956450 ]
#  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
#  crs: "UTM33N"
#  resources: [ "/", "data/", "data/db/" ]
  ais:
    module: "live"
    connection_string: "data/ais.db"
    coords_type: "lonlat"
    interval: 10
 
    #PL STREAM
    address: "195.182.206.250"
    port: 54321
    #scale: 3.0
    #dynamic_scale: True
    #NO STREAM
    # address: "153.44.253.27"
    # port: 5631
    colors:
       "default"             : "#FFFFFF"
    db_fields:
    #   "shipname": "shipname"
    #   "color": "color"
    #   "heading": "heading"
      "last_updated": "timestamp"
 
display:
  colorbar: False
  dark_mode: True
  fullscreen: False
  resolution: 640
  anchor: "center"
  dpi: 96