enc:
  required: True
  type: dict
  schema:
    #set True if you want to display whole uploaded map
    autosize:
      required: False
      type: boolean

    #size of displayed map
    size:
      required: True
      type: list
      maxlength: 2
      schema:
        type: float
        min: 1.0

    #that's where you want top-left corner to be
    origin:
      required: True
      excludes: center
      type: list
      maxlength: 2
      schema:
        type: float

    #that's where you want the center of a map to be
    center:
      required: True
      excludes: origin
      type: list
      maxlength: 2
      schema:
        type: float

    #UTM zone required for coordinates to work correctly
    crs:
      required: True
      type: string

    #depths are required for both formats, if not set they will be assigned default values
    depths:
      required: False
      type: list
      minlength: 1
      schema:
        type: integer
        min: 0

    #you can pick specific S-57 layers you want to extract, default required is LNDARE, DEPARE and COALNE
    S57_layers:
      required: False
      type: list
      minlength: 1
      schema:
        type: string

    #you must put paths to some resources
    resources:
      required: True
      type: list
      minlength: 1
      schema:
        type: string

    weather:
      required: False
      type: dict
      schema:
        PyThor_adress:
          required: False
          type: string
        #in epoch time
        time_start:
          required: False
          type: integer
        time_end:
          required: False
          type: integer
        variables:
          type: list
          required: False
          schema:
            type: string


display:
  required: False
  type: dict
  schema:
    colorbar:
      required: False
      type: boolean

    dark_mode:
      required: False
      type: boolean

    fullscreen:
      required: False
      type: boolean

    resolution:
      required: False
      type: integer

    anchor:
      required: False
      type: string

    dpi:
      required: False
      type: integer
